# Generated by Django 4.0.2 on 2022-02-17 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='phone_number',
            field=models.CharField(default='010-1233-1234', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
