# Generated by Django 4.0.2 on 2022-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
