# Generated by Django 4.0.2 on 2022-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_signup_password_alter_signup_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sign_ups',
            },
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
